### ISSUE TITLE
Cram on windows

### ISSUE THREAD

**Issue by neoroma** [cujojs/cram#21]
Failed to run cram script on windows with
Error: Protocol:c: not supported. 

any help?

**Comment by neoroma** [comment]
> cram index.html --include curl/plugin/domReady --include curl/plugin/text --output app/run.cram.js

http.js:1787
    throw new Error('Protocol:' + options.protocol + ' not supported.');
          ^
Error: Protocol:c: not supported.
    at Object.exports.request (http.js:1787:11)
    at Object.exports.get (http.js:1794:21)
    at loadScriptViaNodeHttp (C:\dev\sandbox\cujojs\node_modules\cram\amd_modules\curl\dist\curl-for-ssjs\curl.js:1518:8)
    at Object.priv.core.loadScript (C:\dev\sandbox\cujojs\node_modules\cram\amd_modules\curl\dist\curl-for-ssjs\curl.js:1485:11)
    at Object.core.fetchResDef (C:\dev\sandbox\cujojs\node_modules\cram\amd_modules\curl\dist\curl-for-ssjs\curl.js:934:9)
    at Object.core.fetchDep (C:\dev\sandbox\cujojs\node_modules\cram\amd_modules\curl\dist\curl-for-ssjs\curl.js:1017:10)
    at getDep (C:\dev\sandbox\cujojs\node_modules\cram\amd_modules\curl\dist\curl-for-ssjs\curl.js:889:21)
    at Object.core.getDeps (C:\dev\sandbox\cujojs\node_modules\cram\amd_modules\curl\dist\curl-for-ssjs\curl.js:871:6)
    at C:\dev\sandbox\cujojs\node_modules\cram\amd_modules\curl\dist\curl-for-ssjs\curl.js:1224:38
    at when (C:\dev\sandbox\cujojs\node_modules\cram\amd_modules\curl\dist\curl-for-ssjs\curl.js:217:11)
npm ERR! cujoJS.com@0.2.0 cram: `cram index.html --include curl/plugin/domReady --include curl/plugin/text --output app/run.cram.js`
npm ERR! `cmd "/c" "cram index.html --include curl/plugin/domReady --include curl/plugin/text --output app/run.cram.js"` failed with 8
npm ERR!
npm ERR! Failed at the cujoJS.com@0.2.0 cram script.
npm ERR! This is most likely a problem with the cujoJS.com package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cram index.html --include curl/plugin/domReady --include curl/plugin/text --output app/run.cram.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls cujoJS.com
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\Program Files (x86)\nodejs\\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js" "run-script" "cram"
npm ERR! cwd C:\dev\sandbox\cujojs
npm ERR! node -v v0.10.2
npm ERR! npm -v 1.2.15
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\dev\sandbox\cujojs\npm-debug.log

**Comment by unscriptable** [comment]
Fixed by latest version (0.7.5). yay :)
