### ISSUE TITLE
cram fails on the seed project

### ISSUE THREAD

**Issue by stanislawosinski** [cujojs/cram#37]
cram fails to build the seed project with the following exception:

```
Compiling wire/wire!app/main
cram failed:  Object function when(promiseOrValue, onFulfilled, onRejected, onProgress) {
                // Get a trusted promise for the input promiseOrValue, and then
                // register promise handlers
                return resolve(promiseOrValue).then(onFulfilled, onRejected, onProgress);
        } has no method 'promise'
TypeError: Object function when(promiseOrValue, onFulfilled, onRejected, onProgress) {
                // Get a trusted promise for the input promiseOrValue, and then
                // register promise handlers
                return resolve(promiseOrValue).then(onFulfilled, onRejected, onProgress);
        } has no method 'promise'
    at fetchNextSpec (e:\repositories\carrotsearch.com\labs\test\lib\wire\builder\cram.js:84:17)
    at e:\repositories\carrotsearch.com\labs\test\lib\when\unfold.js:28:39
    at Object.then (e:\repositories\carrotsearch.com\labs\test\node_modules\cram\amd_modules\when\when.js:207:55)
    at when (e:\repositories\carrotsearch.com\labs\test\node_modules\cram\amd_modules\when\when.js:59:34)
    at e:\repositories\carrotsearch.com\labs\test\lib\when\unfold.js:27:11
    at Object.then (e:\repositories\carrotsearch.com\labs\test\node_modules\cram\amd_modules\when\when.js:207:55)
    at when (e:\repositories\carrotsearch.com\labs\test\node_modules\cram\amd_modules\when\when.js:59:34)
    at unfold (e:\repositories\carrotsearch.com\labs\test\lib\when\unfold.js:25:10)
    at processSpec (e:\repositories\carrotsearch.com\labs\test\lib\wire\builder\cram.js:76:11)
    at e:\repositories\carrotsearch.com\labs\test\lib\wire\builder\cram.js:62:11
```

**Comment by unscriptable** [comment]
Thanks again, @stanislawosinski.  Fixing this in my dev branch.

**Comment by unscriptable** [comment]
This is fixed in the dev branch.

**Comment by stanislawosinski** [comment]
Thanks @unscriptable!

**Comment by unscriptable** [comment]
As part of the next version of seed, I'm thinking that we should stop fighting bower and just let it install in a folder named "bower_components".  This means the next version will install into a different location.  Just FYI.

**Comment by unscriptable** [comment]
Hey @stanislawosinski, let me know if cram+seed is working for you or not.  Thanks!  -- John

**Comment by stanislawosinski** [comment]
Hi John,

I've just verified that cram+seed work perfectly now. The extra bit of documentation around cram in seed is a great idea, it should help people to get started.

S.
