### ISSUE TITLE
Cram not working

### ISSUE THREAD

**Issue by tungd** [cujojs/cram#47]
Steps to produce:

```
git clone gh:cujojs/seed
cd seed
npm install
bower install
npm run cram
```

Stack trace:

```
Compiling wire/wire!app/main
cram failed:  undefined is not a function
TypeError: undefined is not a function
    at processSpec (/home/tung/Projects/seed/bower_components/wire/builder/cram.js:80:11)
    at /home/tung/Projects/seed/bower_components/wire/builder/cram.js:66:11
    at Promise.FulfilledPromise._when (/home/tung/Projects/seed/node_modules/cram/amd_modules/when/when.js:439:48)
    at deliver (/home/tung/Projects/seed/node_modules/cram/amd_modules/when/when.js:108:7)
    at Array.31 (/home/tung/Projects/seed/node_modules/cram/amd_modules/when/when.js:105:63)
    at runHandlers (/home/tung/Projects/seed/node_modules/cram/amd_modules/when/when.js:368:12)
    at drainQueue (/home/tung/Projects/seed/node_modules/cram/amd_modules/when/when.js:811:3)
    at process._tickCallback (node.js:419:13)
```

I tried to modify the paths, or run `cram` manually with different config with no luck.

NPM version: 1.4.26
Node version: v0.10.31

**Comment by unscriptable** [comment]
It seems there's a conflict between curl (used internally by cram), wire's cram plugin, and when 3.x.  Will confer with @briancavalier about a solution.

**Comment by unscriptable** [comment]
Moved the issue to here: https://github.com/cujojs/seed/issues/14
